/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Done at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/transform_data.py': [Errno 2] No such file or directory
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/chaiwatyingsunton/scripts/load_to_sqlite.py': [Errno 2] No such file or directory
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 5, in load_data
    df = pd.read_csv("data/products_clean.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/products_clean.csv'
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 11, in <module>
    clean_data()
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/transform_data.py", line 3, in clean_data
    df = pd.read_csv("data/product_raw.csv")
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/chaiwatyingsunton/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/product_raw.csv'
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 11, in <module>
    load_data()          
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/load_to_sqlite.py", line 6, in load_data
    conn = sqlite3.connect("db/ecommerce.db")
sqlite3.OperationalError: unable to open database file
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 3: data: command not found
Start pipeline at 
Clean data saced!
Data loaded into SQLite!
/Users/chaiwatyingsunton/ecommerce_data_pipeline/run_pipeline.sh: line 6: data: command not found
Pipeline finished at 
Start pipeline at Sat Jun  7 15:11:00 +07 2025
Clean data saced!
Data loaded into SQLite!
Pipeline finished at Sat Jun  7 15:11:02 +07 2025
Start pipeline at Sat Jun  7 15:12:00 +07 2025
Clean data saced!
Data loaded into SQLite!
Pipeline finished at Sat Jun  7 15:12:02 +07 2025
Start pipeline at Sat Jun  7 15:13:00 +07 2025
Clean data saced!
Data loaded into SQLite!
Pipeline finished at Sat Jun  7 15:13:02 +07 2025
Start pipeline at Sat Jun  7 15:14:00 +07 2025
Clean data saced!
Data loaded into SQLite!
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/analyte.py", line 5, in <module>
    conn = sqlite3.connect("db/ecommerce.db")
sqlite3.OperationalError: unable to open database file
Pipeline finished at Sat Jun  7 15:14:03 +07 2025
Start pipeline at Sat Jun  7 15:15:00 +07 2025
Clean data saced!
Data loaded into SQLite!
Traceback (most recent call last):
  File "/Users/chaiwatyingsunton/ecommerce_data_pipeline/scripts/analyte.py", line 5, in <module>
    conn = sqlite3.connect("/Users/chaiwatyingsunton/ecommerce_data_pipelinedb/ecommerce.db")
sqlite3.OperationalError: unable to open database file
Pipeline finished at Sat Jun  7 15:15:02 +07 2025
Start pipeline at Sat Jun  7 15:16:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:16:03 +07 2025
Start pipeline at Sat Jun  7 15:17:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:17:02 +07 2025
Start pipeline at Sat Jun  7 15:18:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:18:03 +07 2025
Start pipeline at Sat Jun  7 15:19:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:19:02 +07 2025
Start pipeline at Sat Jun  7 15:20:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:20:03 +07 2025
Start pipeline at Sat Jun  7 15:21:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:21:02 +07 2025
Start pipeline at Sat Jun  7 15:22:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:22:03 +07 2025
Start pipeline at Sat Jun  7 15:23:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:23:03 +07 2025
Start pipeline at Sat Jun  7 15:24:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:24:02 +07 2025
Start pipeline at Sat Jun  7 15:25:01 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:25:03 +07 2025
Start pipeline at Sat Jun  7 15:26:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:26:03 +07 2025
Start pipeline at Sat Jun  7 15:27:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:27:02 +07 2025
Start pipeline at Sat Jun  7 15:28:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:28:02 +07 2025
Start pipeline at Sat Jun  7 15:29:01 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:29:03 +07 2025
Start pipeline at Sat Jun  7 15:30:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:30:02 +07 2025
Start pipeline at Sat Jun  7 15:31:00 +07 2025
Clean data saced!
Data loaded into SQLite!
           category   avg_price  total_products
0       Electronics  332.498333               6
1          Jewelery  220.995000               4
2    Men'S Clothing   51.057500               4
3  Women'S Clothing   26.286667               6
Pipeline finished at Sat Jun  7 15:31:03 +07 2025
